version: "3.4"
services:
  web:
    build: .
    ports:
      - "9000:9000"
    networks:
      - network
    volumes:
      - ./data:/data
      - ./src:/workspace

networks:
  network:
    driver: bridge