version: 1
# 将信息传播到配置文件的跟日志记录器中
disable_existing_loggers: False

base_dir: &base_dir /data/logs

formatters:
  simple:
    format: "%(asctime)s - %(filename)s -%(name)s -%(levelname)s - %(message)s"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout


  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: !!python/object/apply:os.path.join [ *base_dir , debug.log ]
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: !!python/object/apply:os.path.join [ *base_dir , info.log ]
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: !!python/object/apply:os.path.join [ *base_dir , error.log ]
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  my_module:
    level: ERROR
    handlers: [ console ]
    # 打开日志记录器
    propagate: False

root:
  level: DEBUG
  handlers: [ console, info_file_handler ]